spring.application.name=bebeConforto 
spring.datasource.url=jdbc:postgresql://localhost:5432/bebe_conforto
spring.datasource.username=postgres
spring.datasource.password=08igor

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=uptade
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true